FROM python:3.12-slim

WORKDIR /app

COPY backend/ ./backend/

WORKDIR /app/backend

RUN python -m pip install --upgrade pip
RUN python -m pip install -e .

CMD uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}
