"""initial_schema

Revision ID: 0c1a0521e4d5
Revises: 
Create Date: 2026-05-10 19:54:44.975652
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c1a0521e4d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
